import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar, Sidebar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <Navbar />
          <div className="flex flex-1 overflow-hidden">
            <div className="hidden md:block bg-slate-100 w-[200px]">
              <Sidebar />
            </div>
            <main className="flex-1 overflow-auto p-4 md:p-5">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
