import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar, Sidebar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex h-screen">
          <div className="hidden md:block bg-gray-100 h-full w-[250px] flex-shrink-0">
            <Sidebar />
          </div>
          <div className="flex-1 overflow-hidden p-4 md:p-5 md:max-w-[calc(100%-250px)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
